Change
DHervochon/github-api-testing pull request #2
Opened 2021-06-21 21:39 UTC by DimaMzk

2021-06-24 20:33 UTC, DimaMzk commented
This is a regular Comment

2021-06-24 20:33 UTC, DimaMzk commented
# This Has Some Markdown 🤔

2021-06-24 20:33 UTC, DimaMzk commented
![image](https://user-images.githubusercontent.com/16964252/123328733-c8bcfb80-d4f0-11eb-8899-e2565554c52c.png)
This has an attachment

2021-06-24 20:34 UTC, DimaMzk commented on new.txt
> +These are some cool changes, huh?
Ohhhhh

2021-06-24 20:34 UTC, DimaMzk commented on new.txt
> +One day this will have keyword highlighting,
```suggestion
One day this will have keyword highlighting, one day...
```

2021-06-24 21:19 UTC, DimaMzk reviewed
I just can't stop reviewing this PR, just so many things to critique!

2021-06-25 01:15 UTC, DimaMzk reviewed
Commenting through the API

2021-06-25 01:16 UTC, DimaMzk reviewed
Commenting through the API and closing

2021-06-25 01:30 UTC, DHervochon requested changes
This is terrible! Get good!

2021-06-25 01:44 UTC, DHervochon approved these changes
👍

2021-06-25 01:45 UTC, DHervochon commented
Posting a comment that isn't a review.

2021-06-25 16:33 UTC, DimaMzk commented
Haha wow another comment!

2021-06-25 17:16 UTC, DimaMzk commented
This is a 

**Comment**

With multiple lines

```html
<p>Hello World</p>
```

2021-06-25 18:50 UTC, DHervochon commented
test

2021-06-26 00:28 UTC, closed without merging